name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU and Docker for ARM emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run build inside Debian ARM32 container
        uses: addnab/docker-run-action@v3
        with:
          image: arm32v7/debian:bullseye
          options: --platform linux/arm/v7
          run: |
            apt-get update
            apt-get install -y cmake build-essential git
            mkdir -p build
            cd build
            cmake -DCUSTOM_ST7789_240X240=ON \
                  -DSPI_BUS_CLOCK_DIVISOR=4 \
                  -DGPIO_TFT_DATA_CONTROL=17 \
                  -DGPIO_TFT_RESET_PIN=22 \
                  -DGPIO_TFT_BACKLIGHT=27 \
                  -DSTATISTICS=0 \
                  -DUSE_DMA_TRANSFERS=ON ..
            make -j4

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fbcp-ili9341-arm32-build
          path: build/
