name: Build for Raspberry Pi Zero 2 W

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo'yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gerekli paketleri yükle (CMake, make, GCC vs.)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      # Build klasörü oluştur
      - name: Create build directory
        run: mkdir -p build

      # CMake komutunu çalıştır
      - name: Run CMake
        working-directory: build
        run: |
          cmake -DCUSTOM_ST7789_240X240=ON \
                -DSPI_BUS_CLOCK_DIVISOR=4 \
                -DGPIO_TFT_DATA_CONTROL=17 \
                -DGPIO_TFT_RESET_PIN=22 \
                -DGPIO_TFT_BACKLIGHT=27 \
                -DSTATISTICS=0 \
                -DUSE_DMA_TRANSFERS=ON ..

      # Make ile derle
      - name: Build
        working-directory: build
        run: make -j4

      # Build sonucu artifact olarak kaydet
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fbcp-ili9341-build
          path: build/
